spring:
  application:
    name: LoginAuthetication

  data:
    mongodb:
      url: mongodb+srv://matteo93parisi:clustepass93qterywu@clusterapp.iavl0vj.mongodb.net/autenticazione?retryWrites=true&w=majority&appName=ClusterApp
      database: autenticazione

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:matteo93parisi@gmail.com}
    password: ${MAIL_PASSWORD:ethfxqglellfeuht}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwtSecret: bb7d3fdf9307ab64018da60905d3e0d59937d1fd7bfa089f27c244cdf290d22e
  jwtExpirationMs: 900000
  jwtRefreshExpirationMs: 86400000

  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:defaultPassword}
    email: ${ADMIN:default@email.it}

  confirmationUrl: http://localhost8080/api/v1/auth/confirm?keyConfirm=



